### ISSUE TITLE
Как продолжить редактирование на другом устройстве?

### ISSUE THREAD

**Issue by Alexears** [VityaSchel/SIPacker#43]
Не совсем понимаю как можно продолжить редактировать на другом устройстве? 

Набросал пару вопросов на одном, но например хочу продолжить на рабочем компе или на мобилке, как это осуществить? Простое копирование адреса пака не дало результата, пишет страница не найдена

**Comment by VityaSchel** [comment]
никак, приложение работает полностью клиентсайд, у него нет сервера
